// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestProject.Data.Context;

#nullable disable

namespace TestProject.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20221213105819_Migration202212131656")]
    partial class Migration202212131656
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DamuBala.Entities.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "38815E40-2E91-4033-849F-1202B5A319B8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "224f9a7b-aaa5-4b6d-a0bf-1ed87667a0b5",
                            Email = "manager@project.kz",
                            EmailConfirmed = true,
                            FirstName = "Manager",
                            LastName = "Manager",
                            LockoutEnabled = false,
                            MiddleName = "Manager",
                            NormalizedEmail = "MANAGER@PROJECT.KZ",
                            NormalizedUserName = "MANAGER",
                            PasswordHash = "AQAAAAIAAYagAAAAENyHRZ+gT5dirsYk1RjEo+3TSaV5u9dK8NZ9F+gWo7kpHtxFWbJQI5ujrZoPeYFYdw==",
                            PhoneNumber = "+77085517931",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "00000000-0000-0000-0000-000000000000",
                            TwoFactorEnabled = false,
                            UserName = "manager"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "78A7570F-3CE5-48BA-9461-80283ED1D94D",
                            Name = "manager",
                            NormalizedName = "MANAGER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "38815E40-2E91-4033-849F-1202B5A319B8",
                            RoleId = "78A7570F-3CE5-48BA-9461-80283ED1D94D"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HDocumentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("HTabId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HFolderId");

                    b.HasIndex("HTabId");

                    b.ToTable("HDocumentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HTabId = 1,
                            Name = "Договор оказания услуг"
                        },
                        new
                        {
                            Id = 2,
                            HTabId = 1,
                            Name = "Бюджетная заявка"
                        },
                        new
                        {
                            Id = 3,
                            HTabId = 1,
                            Name = "Техническая спецификация"
                        },
                        new
                        {
                            Id = 4,
                            HTabId = 1,
                            Name = "План-график проведения работ"
                        },
                        new
                        {
                            Id = 5,
                            HTabId = 2,
                            Name = "Техническое задание"
                        },
                        new
                        {
                            Id = 6,
                            HTabId = 2,
                            Name = "Протокол встречи"
                        },
                        new
                        {
                            Id = 7,
                            HTabId = 2,
                            Name = "Спецификация требований к программному обеспечению"
                        },
                        new
                        {
                            Id = 8,
                            HFolderId = 1,
                            HTabId = 3,
                            Name = "Диаграмма классов №"
                        },
                        new
                        {
                            Id = 9,
                            HFolderId = 2,
                            HTabId = 3,
                            Name = "Сценарий №"
                        },
                        new
                        {
                            Id = 10,
                            HFolderId = 3,
                            HTabId = 3,
                            Name = "Описание форматов"
                        },
                        new
                        {
                            Id = 11,
                            HFolderId = 3,
                            HTabId = 3,
                            Name = "Схема интеграционного взаимодействия"
                        },
                        new
                        {
                            Id = 12,
                            HFolderId = 4,
                            HTabId = 3,
                            Name = "Справочник"
                        },
                        new
                        {
                            Id = 13,
                            HFolderId = 4,
                            HTabId = 3,
                            Name = "Реестр служебных сообщений"
                        },
                        new
                        {
                            Id = 14,
                            HFolderId = 4,
                            HTabId = 3,
                            Name = "Реестр ошибок"
                        },
                        new
                        {
                            Id = 15,
                            HFolderId = 5,
                            HTabId = 3,
                            Name = "Макет графического интерфейса"
                        },
                        new
                        {
                            Id = 16,
                            HFolderId = 5,
                            HTabId = 3,
                            Name = "Описание форматов"
                        },
                        new
                        {
                            Id = 17,
                            HTabId = 4,
                            Name = "Сервисы (справочно)"
                        },
                        new
                        {
                            Id = 18,
                            HTabId = 4,
                            Name = "Подключение (справочно)"
                        },
                        new
                        {
                            Id = 19,
                            HTabId = 4,
                            Name = "Исходный проект (справочно)"
                        },
                        new
                        {
                            Id = 20,
                            HFolderId = 6,
                            HTabId = 5,
                            Name = "Тест-план"
                        },
                        new
                        {
                            Id = 21,
                            HFolderId = 6,
                            HTabId = 5,
                            Name = "Протокол тестирования"
                        },
                        new
                        {
                            Id = 22,
                            HFolderId = 7,
                            HTabId = 5,
                            Name = "Тест-кейс №"
                        },
                        new
                        {
                            Id = 23,
                            HFolderId = 8,
                            HTabId = 5,
                            Name = "Чек лист №"
                        },
                        new
                        {
                            Id = 24,
                            HFolderId = 9,
                            HTabId = 5,
                            Name = "Отчет об ошибке №"
                        },
                        new
                        {
                            Id = 25,
                            HTabId = 6,
                            Name = "Акт ввода в опытную эксплуатацию"
                        },
                        new
                        {
                            Id = 26,
                            HTabId = 6,
                            Name = "Акт ввода в промышленную эксплуатацию"
                        },
                        new
                        {
                            Id = 27,
                            HTabId = 6,
                            Name = "Акт приема-передачи"
                        },
                        new
                        {
                            Id = 28,
                            HTabId = 6,
                            Name = "Протокол оказания услуг"
                        },
                        new
                        {
                            Id = 29,
                            HTabId = 6,
                            Name = "Акт выполненных работ"
                        },
                        new
                        {
                            Id = 30,
                            HTabId = 6,
                            Name = "План и методика испытаний"
                        },
                        new
                        {
                            Id = 31,
                            HTabId = 6,
                            Name = "Протокол испытаний"
                        },
                        new
                        {
                            Id = 32,
                            HTabId = 6,
                            Name = "Протокол демонстрации"
                        },
                        new
                        {
                            Id = 33,
                            HTabId = 7,
                            Name = "Договор по сопровождению ИС"
                        },
                        new
                        {
                            Id = 34,
                            HTabId = 7,
                            Name = "Протокол оказания услуг"
                        },
                        new
                        {
                            Id = 35,
                            HTabId = 7,
                            Name = "Акт выполненных работ"
                        },
                        new
                        {
                            Id = 36,
                            HTabId = 7,
                            Name = "Руководство пользователя"
                        },
                        new
                        {
                            Id = 37,
                            HTabId = 7,
                            Name = "Руководство администратора"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HFolderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("HTabId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HTabId");

                    b.ToTable("HFolders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HTabId = 3,
                            Name = "Модели данных"
                        },
                        new
                        {
                            Id = 2,
                            HTabId = 3,
                            Name = "Варианты использования"
                        },
                        new
                        {
                            Id = 3,
                            HTabId = 3,
                            Name = "Интеграционные взаимодействия"
                        },
                        new
                        {
                            Id = 4,
                            HTabId = 3,
                            Name = "Реестры"
                        },
                        new
                        {
                            Id = 5,
                            HTabId = 3,
                            Name = "Графический интерфейс"
                        },
                        new
                        {
                            Id = 6,
                            HTabId = 5,
                            Name = "Глобальные артефакты"
                        },
                        new
                        {
                            Id = 7,
                            HTabId = 5,
                            Name = "Тест-кейсы"
                        },
                        new
                        {
                            Id = 8,
                            HTabId = 5,
                            Name = "Чек-листы"
                        },
                        new
                        {
                            Id = 9,
                            HTabId = 5,
                            Name = "Отчеты"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HPositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HPositions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Аналитик"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Менеджер"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Разработчик Backend"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Разработчик FrontEnd"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Тестировщик"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Дизайнер"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HProjectDesicionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HProjectDesicions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "В процессе выполнения"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Выполнение"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Заморожено"
                        },
                        new
                        {
                            Id = 4,
                            Name = "На сопровождении"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Закрыто"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Отменено"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HProjectStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HProjectStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Инициация"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Анализ и выявление требований"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Проектирование и дизайн"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Разработка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Тестирование"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ввод в эксплуатацию"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сопровождение"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HProjectTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HProjectTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Проект на основе заказа"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Собственный продукт"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Партнерский продукт"
                        });
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HTabEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HTabs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Инициация"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Анализ и выявление требований"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Проектирование и дизайн"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Разработка"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Тестирование"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ввод в эксплуатацию"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Сопровождение"
                        });
                });

            modelBuilder.Entity("TestProject.Models.DocumentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedByUser")
                        .HasColumnType("text");

                    b.Property<int>("HDocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("HFolderId")
                        .HasColumnType("integer");

                    b.Property<int>("HTabId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.Property<int?>("UploadId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HDocumentTypeId");

                    b.HasIndex("HFolderId");

                    b.HasIndex("HTabId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UploadId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("TestProject.Models.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedByUser")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TestProject.Models.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedByUser")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<int>("ProjectDesicionId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectDesicionId");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("ProjectTypeId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TestProject.Models.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedByUser")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TestProject.Models.UploadEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeletedByUser")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("FileScreenName")
                        .HasColumnType("text");

                    b.Property<double>("FileSize")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("text");

                    b.Property<string>("downloadUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Uploads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DamuBala.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DamuBala.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DamuBala.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DamuBala.Entities.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HDocumentTypeEntity", b =>
                {
                    b.HasOne("TestProject.Models.Dictionaries.HFolderEntity", "HFolder")
                        .WithMany()
                        .HasForeignKey("HFolderId");

                    b.HasOne("TestProject.Models.Dictionaries.HTabEntity", "HTab")
                        .WithMany()
                        .HasForeignKey("HTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HFolder");

                    b.Navigation("HTab");
                });

            modelBuilder.Entity("TestProject.Models.Dictionaries.HFolderEntity", b =>
                {
                    b.HasOne("TestProject.Models.Dictionaries.HTabEntity", "HTab")
                        .WithMany()
                        .HasForeignKey("HTabId");

                    b.Navigation("HTab");
                });

            modelBuilder.Entity("TestProject.Models.DocumentEntity", b =>
                {
                    b.HasOne("TestProject.Models.Dictionaries.HDocumentTypeEntity", "HDocumentType")
                        .WithMany()
                        .HasForeignKey("HDocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.Dictionaries.HFolderEntity", "HFolder")
                        .WithMany()
                        .HasForeignKey("HFolderId");

                    b.HasOne("TestProject.Models.Dictionaries.HTabEntity", "HTab")
                        .WithMany()
                        .HasForeignKey("HTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.UploadEntity", "Upload")
                        .WithMany()
                        .HasForeignKey("UploadId");

                    b.Navigation("HDocumentType");

                    b.Navigation("HFolder");

                    b.Navigation("HTab");

                    b.Navigation("Project");

                    b.Navigation("Upload");
                });

            modelBuilder.Entity("TestProject.Models.EmployeeEntity", b =>
                {
                    b.HasOne("TestProject.Models.Dictionaries.HPositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TestProject.Models.ProjectEntity", b =>
                {
                    b.HasOne("TestProject.Models.Dictionaries.HProjectDesicionEntity", "ProjectDesicion")
                        .WithMany()
                        .HasForeignKey("ProjectDesicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.Dictionaries.HProjectStatusEntity", "ProjectStatus")
                        .WithMany()
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.Dictionaries.HProjectTypeEntity", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestProject.Models.TeamEntity", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectDesicion");

                    b.Navigation("ProjectStatus");

                    b.Navigation("ProjectType");

                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
